//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 01:38:08 PM EDT 
//


package org.oasis_open.docs.s_ramp.ns.s_ramp_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DerivedArtifactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DerivedArtifactType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}BaseArtifactType">
 *       &lt;sequence>
 *         &lt;element name="relatedDocument" type="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}documentArtifactTarget"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DerivedArtifactType", propOrder = {
    "relatedDocument"
})
@XmlSeeAlso({
    PolicyAttachment.class,
    PolicyExpression.class,
    AttributeDeclaration.class,
    ElementDeclaration.class,
    WsdlExtension.class,
    XsdType.class,
    WsdlDerivedArtifactType.class
})
public abstract class DerivedArtifactType
    extends BaseArtifactType
{

    @XmlElement(required = true)
    protected DocumentArtifactTarget relatedDocument;

    /**
     * Gets the value of the relatedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentArtifactTarget }
     *     
     */
    public DocumentArtifactTarget getRelatedDocument() {
        return relatedDocument;
    }

    /**
     * Sets the value of the relatedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentArtifactTarget }
     *     
     */
    public void setRelatedDocument(DocumentArtifactTarget value) {
        this.relatedDocument = value;
    }

}
