//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 01:38:08 PM EDT 
//


package org.oasis_open.docs.s_ramp.ns.s_ramp_v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for documentArtifactEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="documentArtifactEnum">
 *   &lt;restriction base="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}baseArtifactEnum">
 *     &lt;enumeration value="DocumentArtifactType"/>
 *     &lt;enumeration value="Document"/>
 *     &lt;enumeration value="XmlDocument"/>
 *     &lt;enumeration value="ExtendedDocument"/>
 *     &lt;enumeration value="XsdDocument"/>
 *     &lt;enumeration value="WsdlDocument"/>
 *     &lt;enumeration value="PolicyDocument"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "documentArtifactEnum")
@XmlEnum(BaseArtifactEnum.class)
public enum DocumentArtifactEnum {

    @XmlEnumValue("DocumentArtifactType")
    DOCUMENT_ARTIFACT_TYPE(BaseArtifactEnum.DOCUMENT_ARTIFACT_TYPE),
    @XmlEnumValue("Document")
    DOCUMENT(BaseArtifactEnum.DOCUMENT),
    @XmlEnumValue("XmlDocument")
    XML_DOCUMENT(BaseArtifactEnum.XML_DOCUMENT),
    @XmlEnumValue("ExtendedDocument")
    EXTENDED_DOCUMENT(BaseArtifactEnum.EXTENDED_DOCUMENT),
    @XmlEnumValue("XsdDocument")
    XSD_DOCUMENT(BaseArtifactEnum.XSD_DOCUMENT),
    @XmlEnumValue("WsdlDocument")
    WSDL_DOCUMENT(BaseArtifactEnum.WSDL_DOCUMENT),
    @XmlEnumValue("PolicyDocument")
    POLICY_DOCUMENT(BaseArtifactEnum.POLICY_DOCUMENT);
    private final BaseArtifactEnum value;

    DocumentArtifactEnum(BaseArtifactEnum v) {
        value = v;
    }

    public BaseArtifactEnum value() {
        return value;
    }

    public static DocumentArtifactEnum fromValue(BaseArtifactEnum v) {
        for (DocumentArtifactEnum c: DocumentArtifactEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
