//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 01:38:08 PM EDT 
//


package org.oasis_open.docs.s_ramp.ns.s_ramp_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Part complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Part">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}NamedWsdlDerivedArtifactType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}xsdTypeTarget" minOccurs="0"/>
 *         &lt;element name="element" type="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}elementTarget" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Part", propOrder = {
    "type",
    "element"
})
public class Part
    extends NamedWsdlDerivedArtifactType
{

    protected XsdTypeTarget type;
    protected ElementTarget element;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link XsdTypeTarget }
     *     
     */
    public XsdTypeTarget getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdTypeTarget }
     *     
     */
    public void setType(XsdTypeTarget value) {
        this.type = value;
    }

    /**
     * Gets the value of the element property.
     * 
     * @return
     *     possible object is
     *     {@link ElementTarget }
     *     
     */
    public ElementTarget getElement() {
        return element;
    }

    /**
     * Sets the value of the element property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementTarget }
     *     
     */
    public void setElement(ElementTarget value) {
        this.element = value;
    }

}
