//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.01 at 01:38:08 PM EDT 
//


package org.oasis_open.docs.s_ramp.ns.s_ramp_v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceImplementationModelEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceImplementationModelEnum">
 *   &lt;restriction base="{http://docs.oasis-open.org/s-ramp/ns/s-ramp-v1.0}baseArtifactEnum">
 *     &lt;enumeration value="ServiceInstance"/>
 *     &lt;enumeration value="ServiceOperation"/>
 *     &lt;enumeration value="ServiceEndpoint"/>
 *     &lt;enumeration value="ServiceOperation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "serviceImplementationModelEnum")
@XmlEnum(BaseArtifactEnum.class)
public enum ServiceImplementationModelEnum {

    @XmlEnumValue("ServiceInstance")
    SERVICE_INSTANCE(BaseArtifactEnum.SERVICE_INSTANCE),
    @XmlEnumValue("ServiceOperation")
    SERVICE_OPERATION(BaseArtifactEnum.SERVICE_OPERATION),
    @XmlEnumValue("ServiceEndpoint")
    SERVICE_ENDPOINT(BaseArtifactEnum.SERVICE_ENDPOINT);
    private final BaseArtifactEnum value;

    ServiceImplementationModelEnum(BaseArtifactEnum v) {
        value = v;
    }

    public BaseArtifactEnum value() {
        return value;
    }

    public static ServiceImplementationModelEnum fromValue(BaseArtifactEnum v) {
        for (ServiceImplementationModelEnum c: ServiceImplementationModelEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
